- platform: darksky
  api_key: 4f0c2460b78be6cf79070f67c6f868d6    
  monitored_conditions:
    - summary
#    - precip_type
    - precip_intensity
    - temperature
#    - dew_point
#    - wind_speed
#    - wind_bearing
    - cloud_cover
    - humidity
#    - nearest_storm_distance
    - hourly_summary
#    - pressure
#    - visibility
#    - ozone
    - temperature_max