######################################################################
##  Shut it all down.  No one is here
######################################################################
- alias: 'Away Mode'
  trigger:
   - platform: state
     entity_id: sensor.family_location
     from: 'Home'
     to: 'Not Home'

  condition:
    - condition: state
      entity_id: sensor.family_location
      state: "Not Home"
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
 
  action:
    service: script.pb_notify
    data_template: 
        value1: >
          {% if is_state('sensor.family_location', 'Home') %}
            Someone is home!
          {% else %}
            Nobody is home!
          {% endif %} 

- alias: 'Home Mode'
  trigger:
   - platform: state
     entity_id: sensor.family_location
     from: 'Not Home'
     to: 'Home'

  condition:
    - condition: state
      entity_id: sensor.family_location
      state: 'Home'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
 
  action:
    service: script.pb_notify
    data_template: 
        value1: >
          {% if is_state('sensor.family_location', 'Home') %}
            Someone is home!
          {% else %}
            Nobody is home!
          {% endif %} 

- alias: 'Work Mode'
  trigger:
   - platform: state
     entity_id: device_tracker.nick_nick
     from: 'not_home'
     to: 'Work'
 
  action:
    service: script.pb_notify
    data_template: 
        value1: >
          {% if is_state('device_tracker.nick_nick', 'Work') %}
            Nick is at Work!
          {% else %}
            Nick is not at Work!
          {% endif %} 
