######################################################################
##  Shut it all down.  No one is here
######################################################################
- alias: 'Away Mode'
  trigger:
   - platform: state
     entity_id: group.family
     state: not_home

  condition:
    - condition: state
      entity_id: group.family
      state: not_home
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
 
  action:
    service: script.pb_notify
    data_template: 
        value1: >
          {% if is_state('group.family', 'home') %}
            Everyone is home!
          {% else %}
            Nobody is home!
          {% endif %} 