###################################
##  Notifies me via IFTTT when something goes down.
###################################

- alias: 'Device Status'
  hide_entity: True
  trigger:
    - platform: state
      entity_id:
        - sensor.plexserver
        - sensor.diskstation
           
  action:
    service: script.pb_notify
    data_template: 
        value1: "Device Status: {{ trigger.entity_id.split('.')[1] }} is {{ trigger.to_state.state }}"
