- alias: "Kodi - Playing"
  hide_entity: False
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_film_time