- alias: 'Nick has left the building'
  hide_entity: False
  
  trigger:
    - platform: state
      entity_id: group.nick
      state: 'not_home'
  
  action:
    - service: script.ifttt_notify
      data_template:
        value1: 'Nick is out'