alias: 'Sunset Stuff on' 
hide_entity: False 
trigger:
  - platform: sun
    event: sunset
    offset: "-00:45:00"
condition:
  - condition: state
    entity_id: group.family
    state: 'home'
action:
  - service: homeassistant.turn_on
    entity_id: group.kitchen_lights
  - service: homeassistant.turn_on
    entity_id: group.dining_room_lights