- alias: "Media player paused/stopped"
  hide_entity: False
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      from: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.standing_lamp